version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567:4566"  # Change the host port to 4567
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
