name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      docker:
        image: localstack/localstack
        options: --privileged
        ports:
          - 4567:4566
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1
          DEBUG: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Run LocalStack
      run: |
        docker-compose -f terraform/localstack/docker-compose.yml up -d

    - name: Export AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=mock_access_key" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=mock_secret_key" >> $GITHUB_ENV

    - name: Initialize Terraform
      working-directory: terraform/localstack
      run: terraform init

    - name: Validate Terraform
      working-directory: terraform/localstack
      run: terraform validate

    - name: Plan Terraform
      working-directory: terraform/localstack
      run: terraform plan

    - name: Apply Terraform
      working-directory: terraform/localstack
      run: terraform apply -auto-approve
